### ISSUE TITLE
Publish extension to Open VSX.

### ISSUE THREAD

**Issue by HarshKapadia2** [Jaakkko/vscode-black-theme#3]
I was trying to use this extension on [GitPod](https://gitpod.io), but it requires extensions to be on [Open VSX](https://github.com/eclipse/openvsx) to be able to use them. Can you please [publish your extension to Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) as well?

Thank you!

**Comment by Jaakkko** [comment]
There you go!
https://open-vsx.org/extension/Jaakko/black
