### ISSUE TITLE
Checkboxes are unreadable sometime

### ISSUE THREAD

**Issue by shaggyfeng** [Jaakkko/vscode-black-theme#4]
In the current VSC, some checkboxes (for example, in the extensions tab, when users want to install a plugin, that install button is unreadable) have very bright background colors and white font color, that makes texts or the check marks unreadable.

Should be a very simple fix, users should be able to fix by themselves, but hope the theme gets a small update.

**Comment by Jaakkko** [comment]
I don't have time for this. But if you have feel free to make a pull request.
