### ISSUE TITLE
Cannot see correctly the install buttons in the extension 

### ISSUE THREAD

**Issue by alpap** [Jaakkko/vscode-black-theme#7]
Cannot see correctly the install buttons in the extension side menu

**Comment by Leila-mekkaoui** [comment]
You can find this problem already answered in the closed issues. However i dont know how to use the pull that was given to fix that issue. so if you know please share !!

**Comment by Jaakkko** [comment]
Are you referring to this https://github.com/Jaakkko/vscode-black-theme/issues/4
